name: Statick on ubuntu-latest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.6', '3.7', '3.8']
    steps:
    - uses: actions/checkout@v2

    - name: Get mkn
      uses: dawidd6/action-download-artifact@v2
      with:
        name: mkn
        branch: master
        workflow: build_nix.yml
        repo: Dekken/maiken

    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - uses: allenevans/set-env@v1.0.0
      with:
        KUL_GIT_CO: --depth 10 # is added to git clone calls

    - run: |
        chmod +x mkn
        export PATH="$PWD:$PATH"
        python3 -m pip install pip --upgrade
        python3 -m pip install -r res/pip_deps.txt --user --upgrade
        XTRA="-tx $PWD/res/ci/travis-linux.yaml" KLOG=4 ./test.sh
