name: Statick on macos-latest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Python ${{ matrix.python-version }}
    runs-on: macos-latest

    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.6', '3.7', '3.8']
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Get mkn
      uses: dawidd6/action-download-artifact@v2
      with:
        name: mkn
        branch: master
        workflow: build_osx.yml
        repo: Dekken/maiken

    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - run: |
        chmod +x mkn
        export PATH="$PWD:$PATH"
        python3 -m pip install pip --upgrade
        python3 -m pip install -r res/pip_deps.txt --user --upgrade
        XTRA="-tx $PWD/res/ci/travis-osx.yaml" KLOG=3 ./res/ci/travis-osx.sh
